package providers

// RegisterAll registers every provider in priority order.
// Order matters: first OwnsModel match wins. Kiro is last (catch-all).
func RegisterAll(reg *Registry, cs *ConfigStore) {
	// 1. BYOK — explicit "byok/" prefix, most specific.
	reg.Register(&BYOK{})

	// 2. Browser-auth providers — specific model names.
	reg.Register(&Canva{})
	reg.Register(&CodeBuddy{})
	reg.Register(&Codex{})
	reg.Register(&Mimo{})
	reg.Register(&Qoder{})

	// 3. Major API-key providers — well-known models.
	reg.Register(&OpenAI{})
	reg.Register(&Anthropic{})
	reg.Register(&GoogleAI{})
	reg.Register(&DeepSeek{})
	reg.Register(&Groq{})
	reg.Register(&Mistral{})
	reg.Register(&Cohere{})
	reg.Register(&Together{})
	reg.Register(&OpenRouter{})
	reg.Register(&Fireworks{})
	reg.Register(&Perplexity{})
	reg.Register(&AI21{})
	reg.Register(&Alibaba{})

	// 4. Smaller / niche API-key providers — alphabetical.
	reg.Register(&ABAB{})
	reg.Register(&AlephAlpha{})
	reg.Register(&Anyscale{})
	reg.Register(&Azure{})
	reg.Register(&Baichuan{})
	reg.Register(&Baidu{})
	reg.Register(&Cerebras{})
	reg.Register(&ChatGLM{})
	reg.Register(&ChimeraGPT{})
	reg.Register(&Clarifai{})
	reg.Register(&CloudflareAI{})
	reg.Register(&Codeium{})
	reg.Register(&CodeLlama{})
	reg.Register(&Cody{})
	reg.Register(&DeepAI{})
	reg.Register(&DeepInfra{})
	reg.Register(&Doubao{})
	reg.Register(&Eden{})
	reg.Register(&EdenAI{})
	reg.Register(&ElectronHub{})
	reg.Register(&EleutherAI{})
	reg.Register(&Ernie{})
	reg.Register(&Fal{})
	reg.Register(&Forefront{})
	reg.Register(&GitHubModels{})
	reg.Register(&GooseAI{})
	reg.Register(&Gradient{})
	reg.Register(&HuggingFace{})
	reg.Register(&Hunyuan{})
	reg.Register(&Hyperbolic{})
	reg.Register(&Inflection{})
	reg.Register(&InternLM{})
	reg.Register(&LambdaAI{})
	reg.Register(&Lepton{})
	reg.Register(&LingYiWanWu{})
	reg.Register(&Mandrill{})
	reg.Register(&MiniMax{})
	reg.Register(&Modal{})
	reg.Register(&MonsterAPI{})
	reg.Register(&Moonshot{})
	reg.Register(&MyShell{})
	reg.Register(&Naga{})
	reg.Register(&NLPCloud{})
	reg.Register(&Novita{})
	reg.Register(&NvidiaNim{})
	reg.Register(&OctoAI{})
	reg.Register(&Oracle{})
	reg.Register(&Pangu{})
	reg.Register(&Pawan{})
	reg.Register(&Phind{})
	reg.Register(&Qwen{})
	reg.Register(&Reka{})
	reg.Register(&Replicate{})
	reg.Register(&RunPod{})
	reg.Register(&SambaNova{})
	reg.Register(&SenseChat{})
	reg.Register(&SiliconCloud{})
	reg.Register(&SiliconFlow{})
	reg.Register(&Skywork{})
	reg.Register(&Spark{})
	reg.Register(&StabilityAI{})
	reg.Register(&Stepfun{})
	reg.Register(&TabNine{})
	reg.Register(&TextSynth{})
	reg.Register(&Tiangong{})
	reg.Register(&Vertex{})
	reg.Register(&WatsonX{})
	reg.Register(&WizardLM{})
	reg.Register(&Writer{})
	reg.Register(&XAI{})
	reg.Register(&Xuanyuan{})
	reg.Register(&Yi{})
	reg.Register(&Zhipu{})
	reg.Register(&ZukiJourney{})

	// 5. Kiro — catch-all, OwnsModel always returns true. MUST be last.
	reg.Register(&Kiro{})
}
